"""
RAG answer generation.

Coordinates the complete Retrieval-Augmented Generation (RAG) pipeline.

Workflow:
1. Retrieve the most relevant document chunks.
2. Build the prompt using the retrieved context.
3. Send the prompt to the language model.
4. Return the generated answer.
"""

from src.llm.client import get_llm
from src.rag.retriever import retrieve
from src.rag.prompt import build_prompt

def answer(question: str) -> str:
    """
    Generate an answer for a user question.

    Args:
        question: User question.

    Returns:
        Answer generated by the language model.
    """

    # Retrieve the most relevant document chunks
    documents = retrieve(question)

    # Build the prompt using the retrieved context
    prompt = build_prompt(
        question=question,
        documents=documents,
    )

    # Create the language model
    llm = get_llm()

    # Generate the response
    response = llm.invoke(prompt)

    return response.content


if __name__ == "__main__":
    # Manual test

    question = input("Question: ")

    response = answer(question)

    print("\nAnswer:\n")
    print(response)